US_STATES = [
            "Birmingham, Alabama",
  "Montgomery, Alabama",
  "Mobile, Alabama",
  "Huntsville, Alabama",
  "Tuscaloosa, Alabama",

  "Anchorage, Alaska",

  "Phoenix, Arizona",
  "Tucson, Arizona",
  "Mesa, Arizona",
  "Chandler, Arizona",
  "Scottsdale, Arizona",

  "Little Rock, Arkansas",
  "Fayetteville, Arkansas",
  "Fort Smith, Arkansas",
  "Springdale, Arkansas",

  "Los Angeles, California",
  "San Diego, California",
  "San Jose, California",
  "San Francisco, California",
  "Fresno, California",
  "Sacramento, California",
  "Long Beach, California",
  "Oakland, California",
  "Bakersfield, California",
  "Anaheim, California",
  "Riverside, California",
  "Stockton, California",
  "Irvine, California",
  "Chula Vista, California",
  "Fremont, California",
  "San Bernardino, California",
  "Modesto, California",
  "Oxnard, California",
  "Fontana, California",
  "Moreno Valley, California",
  "Huntington Beach, California",
  "Glendale, California",
  "Santa Clarita, California",
  "Garden Grove, California",
  "Santa Rosa, California",
  "Oceanside, California",
  "Rancho Cucamonga, California",
  "Ontario, California",
  "Elk Grove, California",
  "Corona, California",
  "Lancaster, California",
  "Palmdale, California",
  "Hayward, California",
  "Salinas, California",
  "Pomona, California",
  "Escondido, California",
  "Sunnyvale, California",
  "Torrance, California",
  "Pasadena, California",
  "Orange, California",
  "Fullerton, California",
  "Roseville, California",
  "Visalia, California",
  "Concord, California",
  "Thousand Oaks, California",
  "Simi Valley, California",

    "Denver, Colorado",
  "Colorado Springs, Colorado",
  "Aurora, Colorado",
  "Fort Collins, Colorado",
  "Boulder, Colorado",
  "Lakewood, Colorado",
  "Thornton, Colorado",
  "Arvada, Colorado",
  "Pueblo, Colorado",
  "Greeley, Colorado",

  "Hartford, Connecticut",
  "New Haven, Connecticut",
  "Stamford, Connecticut",
  "Bridgeport, Connecticut",
  "Waterbury, Connecticut",
  "Danbury, Connecticut",

  "Dover, Delaware",

"Miami, Florida",
  "Orlando, Florida",
  "Tampa, Florida",
  "Jacksonville, Florida",
  "St. Petersburg, Florida",
  "Fort Lauderdale, Florida",
  "Hialeah, Florida",
  "Tallahassee, Florida",
  "Gainesville, Florida",
  "Sarasota, Florida",
  "Pensacola, Florida",

  "Atlanta, Georgia",
  "Savannah, Georgia",
  "Augusta, Georgia",
  "Columbus, Georgia",
  "Macon, Georgia",
  "Athens, Georgia",
  "Sandy Springs, Georgia",

  "Honolulu, Hawaii",

  "Boise, Idaho",
  "Nampa, Idaho",
  "Coeur d'Alene, Idaho",
  "Meridian, Idaho",
  "Idaho Falls, Idaho",

    "Chicago, Illinois",
  "Springfield, Illinois",
  "Aurora, Illinois",
  "Naperville, Illinois",
  "Rockford, Illinois",
  "Joliet, Illinois",
  "Peoria, Illinois",
  "Elgin, Illinois",

  "Indianapolis, Indiana",
  "Fort Wayne, Indiana",
  "Evansville, Indiana",
  "South Bend, Indiana",
  "Carmel, Indiana",
  "Lafayette, Indiana",

#   "Des Moines, Iowa",
#   "Cedar Rapids, Iowa",
#   "Davenport, Iowa",
#   "Sioux City, Iowa",
#   "Iowa City, Iowa",
#   "Waterloo, Iowa",
#   "Ames, Iowa",
#   "West Des Moines, Iowa",

"Wichita, Kansas",
  "Overland Park, Kansas",
  "Kansas City, Kansas",
  "Topeka, Kansas",
  "Olathe, Kansas",

  "Louisville, Kentucky",
  "Lexington, Kentucky",

  "New Orleans, Louisiana",
  "Baton Rouge, Louisiana",
  "Shreveport, Louisiana",
  "Lafayette, Louisiana",
  "Lake Charles, Louisiana",
  "Monroe, Louisiana",

   "Portland, Maine",

  "Baltimore, Maryland",
  "Frederick, Maryland",
  "Hagerstown, Maryland",

  "Boston, Massachusetts",
  "Worcester, Massachusetts",
  "Springfield, Massachusetts",
  "Cambridge, Massachusetts",
  "Lowell, Massachusetts",

  "Detroit, Michigan",
  "Grand Rapids, Michigan",
  "Lansing, Michigan",
  "Ann Arbor, Michigan",
  "Flint, Michigan",
  "Warren, Michigan",
  "Sterling Heights, Michigan",
  "Kalamazoo, Michigan",

#   "Minneapolis, Minnesota",
#   "Saint Paul, Minnesota",
#   "Rochester, Minnesota",
#   "Duluth, Minnesota",
#   "Bloomington, Minnesota",
#   "Brooklyn Park, Minnesota",
#   "Plymouth, Minnesota",
#   "Maple Grove, Minnesota",

#   "Jackson, Mississippi",
#   "Gulfport, Mississippi",
#   "Hattiesburg, Mississippi",
#   "Biloxi, Mississippi",
#   "Tupelo, Mississippi",
#   "Meridian, Mississippi",
#   "Southaven, Mississippi",
#   "Olive Branch, Mississippi",

#   "St. Louis, Missouri",
#   "Kansas City, Missouri",
#   "Springfield, Missouri",
#   "Columbia, Missouri",
#   "Independence, Missouri",
#   "Lee’s Summit, Missouri",
#   "O’Fallon, Missouri",
#   "St. Joseph, Missouri",

#   "Billings, Montana",
#   "Missoula, Montana",
#   "Great Falls, Montana",
#   "Bozeman, Montana",
#   "Helena, Montana",
#   "Butte, Montana",
#   "Kalispell, Montana",
#   "Belgrade, Montana",

#   "Omaha, Nebraska",
#   "Lincoln, Nebraska",
#   "Bellevue, Nebraska",
#   "Grand Island, Nebraska",
#   "Kearney, Nebraska",
#   "Fremont, Nebraska",
#   "North Platte, Nebraska",
#   "Hastings, Nebraska",

#   "Las Vegas, Nevada",
#   "Reno, Nevada",
#   "Henderson, Nevada",
#   "Carson City, Nevada",
#   "Sparks, Nevada",
#   "North Las Vegas, Nevada",
#   "Elko, Nevada",
#   "Mesquite, Nevada",

#   "Manchester, New Hampshire",
#   "Nashua, New Hampshire",
#   "Concord, New Hampshire",
#   "Dover, New Hampshire",
#   "Rochester, New Hampshire",
#   "Portsmouth, New Hampshire",
#   "Laconia, New Hampshire",

#   "Newark, New Jersey",
#   "Jersey City, New Jersey",
#   "Paterson, New Jersey",
#   "Elizabeth, New Jersey",
#   "Trenton, New Jersey",
#   "Camden, New Jersey",
#   "Clifton, New Jersey",
#   "Passaic, New Jersey",

#   "Albuquerque, New Mexico",
#   "Santa Fe, New Mexico",
#   "Las Cruces, New Mexico",
#   "Roswell, New Mexico",
#   "Rio Rancho, New Mexico",
#   "Farmington, New Mexico",
#   "Hobbs, New Mexico",
#   "Gallup, New Mexico",

  "Buffalo, New York",
  "Rochester, New York",
  "Yonkers, New York",
  "Albany, New York",
  "Syracuse, New York",
  "New Rochelle, New York",
  "Utica, New York",
  "White Plains, New York",

#   "Charlotte, North Carolina",
#   "Raleigh, North Carolina",
#   "Durham, North Carolina",
#   "Greensboro, North Carolina",
#   "Winston-Salem, North Carolina",
#   "Fayetteville, North Carolina",
#   "Cary, North Carolina",
#   "High Point, North Carolina",

#   "Fargo, North Dakota",
#   "Bismarck, North Dakota",
#   "Grand Forks, North Dakota",
#   "Minot, North Dakota",
#   "West Fargo, North Dakota",
#   "Williston, North Dakota",

  "Columbus, Ohio",
  "Cleveland, Ohio",
  "Cincinnati, Ohio",
  "Toledo, Ohio",
  "Akron, Ohio",
  "Dayton, Ohio",
  "Canton, Ohio",
  "Youngstown, Ohio",
  "Lorain, Ohio",

#   "Oklahoma City, Oklahoma",
#   "Tulsa, Oklahoma",
#   "Norman, Oklahoma",
#   "Edmond, Oklahoma",
#   "Lawton, Oklahoma",
#   "Broken Arrow, Oklahoma",
#   "Moore, Oklahoma",
#   "Midwest City, Oklahoma",

#   "Portland, Oregon",
#   "Eugene, Oregon",
#   "Salem, Oregon",
#   "Gresham, Oregon",
#   "Bend, Oregon",
#   "Beaverton, Oregon",
#   "Medford, Oregon",
#   "Hillsboro, Oregon",

#   "Philadelphia, Pennsylvania",
#   "Pittsburgh, Pennsylvania",
#   "Allentown, Pennsylvania",
#   "Harrisburg, Pennsylvania",
#   "Lancaster, Pennsylvania",
#   "Erie, Pennsylvania",
#   "Reading, Pennsylvania",
#   "Scranton, Pennsylvania",
#   "Bethlehem, Pennsylvania",

#   "Providence, Rhode Island",
#   "Warwick, Rhode Island",
#   "Cranston, Rhode Island",
#   "Pawtucket, Rhode Island",
#   "Woonsocket, Rhode Island",
#   "Newport, Rhode Island",

#   "Charleston, South Carolina",
#   "Columbia, South Carolina",
#   "Greenville, South Carolina",
#   "Myrtle Beach, South Carolina",
#   "Spartanburg, South Carolina",
#   "Rock Hill, South Carolina",
#   "Summerville, South Carolina",
#   "Florence, South Carolina",

#   "Sioux Falls, South Dakota",
#   "Rapid City, South Dakota",
#   "Aberdeen, South Dakota",
#   "Brookings, South Dakota",
#   "Watertown, South Dakota",
#   "Mitchell, South Dakota",

#   "Nashville, Tennessee",
#   "Memphis, Tennessee",
#   "Knoxville, Tennessee",
#   "Chattanooga, Tennessee",
#   "Clarksville, Tennessee",
#   "Murfreesboro, Tennessee",
#   "Franklin, Tennessee",
#   "Johnson City, Tennessee",

#   "Houston, Texas",
#   "Dallas, Texas",
#   "Austin, Texas",
#   "San Antonio, Texas",
#   "Fort Worth, Texas",
#   "El Paso, Texas",
#   "Arlington, Texas",
#   "Corpus Christi, Texas",
#   "Plano, Texas",
#   "Laredo, Texas",
#   "Lubbock, Texas",

#   "Salt Lake City, Utah",
#   "Provo, Utah",
#   "Ogden, Utah",
#   "St. George, Utah",
#   "Sandy, Utah",
#   "West Valley City, Utah",
#   "Layton, Utah",
#   "Logan, Utah",

#   "Burlington, Vermont",
#   "Montpelier, Vermont",
#   "Rutland, Vermont",
#   "Barre, Vermont",
#   "St. Albans, Vermont",
#   "Brattleboro, Vermont",

  "Virginia Beach, Virginia",
  "Richmond, Virginia",
  "Norfolk, Virginia",
  "Arlington, Virginia",
  "Alexandria, Virginia",
  "Chesapeake, Virginia",
  "Newport News, Virginia",
  "Hampton, Virginia",

  "Seattle, Washington",
  "Spokane, Washington",
  "Tacoma, Washington",
  "Vancouver, Washington",
  "Bellevue, Washington",
  "Everett, Washington",
  "Kent, Washington",
  "Renton, Washington",

  "Charleston, West Virginia",
  "Morgantown, West Virginia",
  "Huntington, West Virginia",

#   "Milwaukee, Wisconsin",
#   "Madison, Wisconsin",
#   "Green Bay, Wisconsin",
#   "Kenosha, Wisconsin",
#   "Appleton, Wisconsin",
#   "Eau Claire, Wisconsin",
#   "Waukesha, Wisconsin",
#   "Oshkosh, Wisconsin",

#   "Cheyenne, Wyoming",
#   "Casper, Wyoming",
#   "Laramie, Wyoming",
#   "Gillette, Wyoming",
#   "Rock Springs, Wyoming",
#   "Sheridan, Wyoming",
#   "Evanston, Wyoming"

           "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
            "New Hampshire", "New Jersey", "New Mexico",
            "North Carolina", "North Dakota", "Oklahoma", "Oregon",
            "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
            "Tennessee", "Texas", "Utah", "Vermont", "Wisconsin", "Wyoming"
        ]