US_STATES = [
  "Birmingham, Alabama, United States",
  "Montgomery, Alabama, United States",
  "Mobile, Alabama, United States",
  "Huntsville, Alabama, United States",
  "Tuscaloosa, Alabama, United States",

  "Anchorage, Alaska, United States",

  "Phoenix, Arizona, United States",
  "Tucson, Arizona, United States",
  "Mesa, Arizona, United States",
  "Chandler, Arizona, United States",
  "Scottsdale, Arizona, United States",

  "Little Rock, Arkansas, United States",
  "Fayetteville, Arkansas, United States",
  "Fort Smith, Arkansas, United States",
  "Springdale, Arkansas, United States",

  "Los Angeles, California, United States",
  "San Diego, California, United States",
  "San Jose, California, United States",
  "San Francisco, California, United States",
  "Fresno, California, United States",
  "Sacramento, California, United States",
  "Long Beach, California, United States",
  "Oakland, California, United States",
  "Bakersfield, California, United States",
  "Anaheim, California, United States",
  "Riverside, California, United States",
  "Stockton, California, United States",
  "Irvine, California, United States",
  "Chula Vista, California, United States",
  "Fremont, California, United States",
  "San Bernardino, California, United States",
  "Modesto, California, United States",
  "Oxnard, California, United States",
  "Fontana, California, United States",
  "Moreno Valley, California, United States",
  "Huntington Beach, California, United States",
  "Glendale, California, United States",
  "Santa Clarita, California, United States",
  "Garden Grove, California, United States",
  "Santa Rosa, California, United States",
  "Oceanside, California, United States",
  "Rancho Cucamonga, California, United States",
  "Ontario, California, United States",
  "Elk Grove, California, United States",
  "Corona, California, United States",
  "Lancaster, California, United States",
  "Palmdale, California, United States",
  "Hayward, California, United States",
  "Salinas, California, United States",
  "Pomona, California, United States",
  "Escondido, California, United States",
  "Sunnyvale, California, United States",
  "Torrance, California, United States",
  "Pasadena, California, United States",
  "Orange, California, United States",
  "Fullerton, California, United States",
  "Roseville, California, United States",
  "Visalia, California, United States",
  "Concord, California, United States",
  "Thousand Oaks, California, United States",
  "Simi Valley, California, United States",

  "Denver, Colorado, United States",
  "Colorado Springs, Colorado, United States",
  "Aurora, Colorado, United States",
  "Fort Collins, Colorado, United States",
  "Boulder, Colorado, United States",
  "Lakewood, Colorado, United States",
  "Thornton, Colorado, United States",
  "Arvada, Colorado, United States",
  "Pueblo, Colorado, United States",
  "Greeley, Colorado, United States",

  "Hartford, Connecticut, United States",
  "New Haven, Connecticut, United States",
  "Stamford, Connecticut, United States",
  "Bridgeport, Connecticut, United States",
  "Waterbury, Connecticut, United States",
  "Danbury, Connecticut, United States",

  "Dover, Delaware, United States",

  "Miami, Florida, United States",
  "Orlando, Florida, United States",
  "Tampa, Florida, United States",
  "Jacksonville, Florida, United States",
  "St. Petersburg, Florida, United States",
  "Fort Lauderdale, Florida, United States",
  "Hialeah, Florida, United States",
  "Tallahassee, Florida, United States",
  "Gainesville, Florida, United States",
  "Sarasota, Florida, United States",
  "Pensacola, Florida, United States",

  "Atlanta, Georgia, United States",
  "Savannah, Georgia, United States",
  "Augusta, Georgia, United States",
  "Columbus, Georgia, United States",
  "Macon, Georgia, United States",
  "Athens, Georgia, United States",
  "Sandy Springs, Georgia, United States",

  "Honolulu, Hawaii, United States",

  "Boise, Idaho, United States",
  "Nampa, Idaho, United States",
  "Coeur d'Alene, Idaho, United States",
  "Meridian, Idaho, United States",
  "Idaho Falls, Idaho, United States",

  "Chicago, Illinois, United States",
  "Springfield, Illinois, United States",
  "Aurora, Illinois, United States",
  "Naperville, Illinois, United States",
  "Rockford, Illinois, United States",
  "Joliet, Illinois, United States",
  "Peoria, Illinois, United States",
  "Elgin, Illinois, United States",

  "Indianapolis, Indiana, United States",
  "Fort Wayne, Indiana, United States",
  "Evansville, Indiana, United States",
  "South Bend, Indiana, United States",
  "Carmel, Indiana, United States",
  "Lafayette, Indiana, United States",

  "Des Moines, Iowa, United States",
  "Cedar Rapids, Iowa, United States",
  "Davenport, Iowa, United States",
  "Sioux City, Iowa, United States",
  "Iowa City, Iowa, United States",
  "Waterloo, Iowa, United States",

  "Wichita, Kansas, United States",
  "Overland Park, Kansas, United States",
  "Kansas City, Kansas, United States",
  "Topeka, Kansas, United States",
  "Olathe, Kansas, United States",

  "Louisville, Kentucky, United States",
  "Lexington, Kentucky, United States",

  "New Orleans, Louisiana, United States",
  "Baton Rouge, Louisiana, United States",
  "Shreveport, Louisiana, United States",
  "Lafayette, Louisiana, United States",
  "Lake Charles, Louisiana, United States",
  "Monroe, Louisiana, United States",

  "Portland, Maine, United States",

  "Baltimore, Maryland, United States",
  "Frederick, Maryland, United States",
  "Hagerstown, Maryland, United States",

  "Boston, Massachusetts, United States",
  "Worcester, Massachusetts, United States",
  "Springfield, Massachusetts, United States",
  "Cambridge, Massachusetts, United States",
  "Lowell, Massachusetts, United States",

  "Detroit, Michigan, United States",
  "Grand Rapids, Michigan, United States",
  "Lansing, Michigan, United States",
  "Ann Arbor, Michigan, United States",
  "Flint, Michigan, United States",
  "Warren, Michigan, United States",
  "Sterling Heights, Michigan, United States",
  "Kalamazoo, Michigan, United States",

  "Minneapolis, Minnesota, United States",
  "Rochester, Minnesota, United States",
  "Duluth, Minnesota, United States",

  "Jackson, Mississippi, United States",
  "Gulfport, Mississippi, United States",

  "St. Louis, Missouri, United States",
  "Kansas City, Missouri, United States",
  "Springfield, Missouri, United States",
  "Columbia, Missouri, United States",
  "Independence, Missouri, United States",

  "Billings, Montana, United States",

  "Omaha, Nebraska, United States",
  "Lincoln, Nebraska, United States",

  "Las Vegas, Nevada, United States",
  "Reno, Nevada, United States",
  "Henderson, Nevada, United States",
  "Sparks, Nevada, United States",
  "North Las Vegas, Nevada, United States",

  "Manchester, New Hampshire, United States",
  "Nashua, New Hampshire, United States",

  "Newark, New Jersey, United States",
  "Jersey City, New Jersey, United States",
  "Paterson, New Jersey, United States",
  "Elizabeth, New Jersey, United States",
  "Trenton, New Jersey, United States",

  "Albuquerque, New Mexico, United States",
  "Santa Fe, New Mexico, United States",
  "Las Cruces, New Mexico, United States",

  "Buffalo, New York, United States",
  "Rochester, New York, United States",
  "Yonkers, New York, United States",
  "Albany, New York, United States",
  "Syracuse, New York, United States",
  "New Rochelle, New York, United States",
  "Utica, New York, United States",
  "White Plains, New York, United States",

#   "Charlotte, North Carolina, United States",
#   "Raleigh, North Carolina, United States",
#   "Durham, North Carolina, United States",
#   "Greensboro, North Carolina, United States",
#   "Winston-Salem, North Carolina, United States",
#   "Fayetteville, North Carolina, United States",
#   "Cary, North Carolina, United States",
#   "High Point, North Carolina, United States",

#   "Fargo, North Dakota, United States",
#   "Bismarck, North Dakota, United States",
#   "Grand Forks, North Dakota, United States",
#   "Minot, North Dakota, United States",
#   "West Fargo, North Dakota, United States",
#   "Williston, North Dakota, United States",

  "Columbus, Ohio, United States",
  "Cleveland, Ohio, United States",
  "Cincinnati, Ohio, United States",
  "Toledo, Ohio, United States",
  "Akron, Ohio, United States",
  "Dayton, Ohio, United States",
  "Canton, Ohio, United States",
  "Youngstown, Ohio, United States",
  "Lorain, Ohio, United States",

  "Oklahoma City, Oklahoma, United States",
  "Tulsa, Oklahoma, United States",
  "Norman, Oklahoma, United States",
  "Lawton, Oklahoma, United States",
  "Broken Arrow, Oklahoma, United States",

  "Portland, Oregon, United States",
  "Eugene, Oregon, United States",
  "Salem, Oregon, United States",
  "Gresham, Oregon, United States",
  "Bend, Oregon, United States",
  "Medford, Oregon, United States",
  "Hillsboro, Oregon, United States",

  "Philadelphia, Pennsylvania, United States",
  "Pittsburgh, Pennsylvania, United States",
  "Allentown, Pennsylvania, United States",
  "Harrisburg, Pennsylvania, United States",
  "Lancaster, Pennsylvania, United States",
  "Erie, Pennsylvania, United States",
  "Reading, Pennsylvania, United States",
  "Scranton, Pennsylvania, United States",

  "Providence, Rhode Island, United States",

#   "Charleston, South Carolina, United States",
#   "Columbia, South Carolina, United States",
#   "Greenville, South Carolina, United States",
#   "Myrtle Beach, South Carolina, United States",
#   "Spartanburg, South Carolina, United States",
#   "Rock Hill, South Carolina, United States",
#   "Summerville, South Carolina, United States",
#   "Florence, South Carolina, United States",

#   "Sioux Falls, South Dakota, United States",
#   "Rapid City, South Dakota, United States",
#   "Aberdeen, South Dakota, United States",
#   "Brookings, South Dakota, United States",
#   "Watertown, South Dakota, United States",
#   "Mitchell, South Dakota, United States",

  "Nashville, Tennessee, United States",
  "Memphis, Tennessee, United States",
  "Knoxville, Tennessee, United States",
  "Chattanooga, Tennessee, United States",
  "Clarksville, Tennessee, United States",
  "Murfreesboro, Tennessee, United States",
  "Johnson City, Tennessee, United States",

  "Houston, Texas, United States",
  "Dallas, Texas, United States",
  "Austin, Texas, United States",
  "San Antonio, Texas, United States",
  "Fort Worth, Texas, United States",
  "El Paso, Texas, United States",
  "Arlington, Texas, United States",
  "Corpus Christi, Texas, United States",
  "Plano, Texas, United States",
  "Laredo, Texas, United States",
  "Lubbock, Texas, United States",

  "Salt Lake City, Utah, United States",
  "Provo, Utah, United States",
  "Ogden, Utah, United States",
  "St. George, Utah, United States",
  "West Valley City, Utah, United States",
  "Logan, Utah, United States",

  "Burlington, Vermont, United States",

  "Virginia Beach, Virginia, United States",
  "Richmond, Virginia, United States",
  "Norfolk, Virginia, United States",
  "Arlington, Virginia, United States",
  "Alexandria, Virginia, United States",
  "Chesapeake, Virginia, United States",
  "Newport News, Virginia, United States",
  "Hampton, Virginia, United States",

  "Seattle, Washington, United States",
  "Spokane, Washington, United States",
  "Tacoma, Washington, United States",
  "Vancouver, Washington, United States",
  "Bellevue, Washington, United States",
  "Everett, Washington, United States",
  "Kent, Washington, United States",
  "Renton, Washington, United States",

  "Charleston, West Virginia, United States",
  "Morgantown, West Virginia, United States",
  "Huntington, West Virginia, United States",

  "Milwaukee, Wisconsin, United States",
  "Madison, Wisconsin, United States",
  "Green Bay, Wisconsin, United States",
  "Kenosha, Wisconsin, United States",
  "Appleton, Wisconsin, United States",
  "Eau Claire, Wisconsin, United States",

  "North Carolina", "North Dakota", "South Carolina", "South Dakota",
]

CA_STATES = [
  "Toronto, Ontario, Canada",
  "Ottawa, Ontario, Canada",
  "Mississauga, Ontario, Canada",
  "Brampton, Ontario, Canada",
  "Hamilton, Ontario, Canada",

  "Montreal, Quebec, Canada",
  "Quebec City, Quebec, Canada",
  "Laval, Quebec, Canada",
  "Gatineau, Quebec, Canada",
  "Longueuil, Quebec, Canada",

  "Vancouver, British Columbia, Canada",
  "Victoria, British Columbia, Canada",
  "Surrey, British Columbia, Canada",
  "Burnaby, British Columbia, Canada",
  "Richmond, British Columbia, Canada",

  "Calgary, Alberta, Canada",
  "Edmonton, Alberta, Canada",
  "Red Deer, Alberta, Canada",
  "Lethbridge, Alberta, Canada",

  "Winnipeg, Manitoba, Canada",

  "Saskatoon, Saskatchewan, Canada",
  "Regina, Saskatchewan, Canada",

  "Halifax, Nova Scotia, Canada",

  "Moncton, New Brunswick, Canada",
  "Dieppe, New Brunswick, Canada",

  "St. John's, Newfoundland and Labrador, Canada",
]